; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:application_stm32f0]
platform = ststm32
board = xboxhdmi_stm32f03
framework = stm32cube
board_build.ldscript = src/application/application.ld
build_src_filter =
	+<application/*.c>
	+<application/*.cpp>
	+<shared/adv7511.cpp>
	+<shared/adv7511_i2c.cpp>
	+<shared/adv7511_xbox.cpp>
	+<shared/crc32.cpp>
	+<shared/debug.cpp>
	+<shared/error_handler.cpp>
	+<shared/flash.cpp>
	+<shared/gpio.cpp>
	+<shared/xbox_video_standalone.cpp>
	+<shared/stm32f0/*.c>
build_flags =
	-Isrc
	-Isrc/application
	-Isrc/shared
	-Isrc/shared/stm32f0

[env:bootloader_stm32f0]
platform = ststm32
board = xboxhdmi_stm32f03
framework = stm32cube
board_build.ldscript = src/bootloader/bootloader.ld
build_src_filter =
	+<bootloader/*.c>
	+<bootloader/*.cpp>
	+<shared/adv7511.cpp>
	+<shared/adv7511_i2c.cpp>
	+<shared/adv7511_xbox.cpp>
	+<shared/crc32.cpp>
	+<shared/debug.cpp>
	+<shared/error_handler.cpp>
	+<shared/flash.cpp>
	+<shared/gpio.cpp>
	+<shared/xbox_video_standalone.cpp>
	+<shared/stm32f0/*.c>
build_flags =
	-Isrc
	-Isrc/bootloader
	-Isrc/shared
	-Isrc/shared/stm32f0

[env:combined_stm32f0]
platform = ststm32
board = xboxhdmi_stm32f03
framework = stm32cube
build_src_filter = +<shared/dummy.c>
extra_scripts = scripts/combine_firmware.py
